controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

dashboard_widgets:
    resource: "@LleDashboardBundle/Resources/config/routes.yaml"

credential:
    resource: "@LleCredentialBundle/Resources/config/routes.yaml"

hermes:
  resource: "@LleHermesBundle/Resources/config/routes.xml"
  prefix: /hermes

lle_pdf_generator:
    resource: "@LlePdfGeneratorBundle/Resources/routing/routes.yaml"
    prefix: /